// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa_cdD6Im6ZSjXqAT_oh144AZoR6Z941M',
    appId: '1:550519095432:android:05c676925fa782a27a5f3d',
    messagingSenderId: '550519095432',
    projectId: 'rishta-app-316aa',
    storageBucket: 'rishta-app-316aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWRXsPM75NO-Nw31pFB8CfCY3Pz9N2o_0',
    appId: '1:550519095432:ios:44c65e1ea41857c47a5f3d',
    messagingSenderId: '550519095432',
    projectId: 'rishta-app-316aa',
    storageBucket: 'rishta-app-316aa.firebasestorage.app',
    iosClientId: '550519095432-5qcabgkbdiqoqmdv2v08kc6n48vuuor4.apps.googleusercontent.com',
    iosBundleId: 'com.example.rishta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBysS0XXNnvts4KzFivHYQySfvbgEF297A',
    appId: '1:550519095432:web:c2f53c4cfd0a58907a5f3d',
    messagingSenderId: '550519095432',
    projectId: 'rishta-app-316aa',
    authDomain: 'rishta-app-316aa.firebaseapp.com',
    storageBucket: 'rishta-app-316aa.firebasestorage.app',
    measurementId: 'G-6D2M3SWKH3',
  );
}
